const TEXT={
    WELCOME_BACK_TO_CERTIFY:"Welcome back to CertifyRecruit.",
    HI_THERE:" Hi there!",
    LOG_IN_WITH_GOOGLE:" Log in with Google",
    OR:"or",
    EMAIL:"Email",
    PASSWORD:"Password",
    FORGOT_PASSWORD:"Forgot password?",
    LOG_IN:"Log In",
    DONT_HAVE_AN_ACCOUNT:"Don’t have an account?",
    SIGN_UP:"Sign up",
    Get_Started:"Get Started!",
    YOUR_NEW_JOURNEY_BEGINS_NOW:"Your New Journey Begins Now.",
    SIGN_UP_WITH_GOOGLE:"Sign up with Google",
    ALREADY_HAVE_AN_ACCOUNT:"Already have an account?",
    SET_NEW_PASSWORD:"Set new password",
    MUST_BE_AT_LEAST_CHARACTERS:"Must be at least 8 characters",
    CONFIRM_PASSWORD:"Confirm password",
    RESET_PASSWORD:"Reset Password",
    CANCEL:"Cancel",
    YOUR_PASSWORD_HAS_BEEN_RESET:"your password has been reset",
    SUCCESSFULLY:"Successfully",
    GO_TO_LOGIN:"Go to login",
    THANK_YOU_FOR_SIGN_UP:"Thank you for sign up!",
    PLEASE_SELECT_OPTION_TO_RECEIVE_PASSWORD_RESET_LINK:"Please select option to receive password reset link.",
    RESET_VIA_EMAIL:"Reset via Email",
    YOU_WILL_BE_PROVIDE_A_UNIQUE:"You will be provide a unique password reset link to your registered email address.",
    SEND:"Send",
    COMPANY_INFO:"Company Info",
    JOB_TITLE:"Job title",
    LOCATION:"Location",
    DONE:"Done",
    ADD_EMPLOYEE:"Add Employee",
    NAME:"Name",
    DEPARTMENT:"Department",
    EXPERIENCE:"Experience",
    SCORE:"Score",
    ACTIVE_JOB:"Active Job",
    JOB_POST:"Job Post",
    USER_INTERFACE_EXPERT:"User Interface Expert (WFH)",
    TWO_WEEKS_AGO:"2 weeks ago",
    EDIT:"Edit",
    DELETE:"Delete",
    VIEW:"View",
    JOB_DETAILS:"Job details",
    CITY_NAMES:"Surat, Gujrat, India.",
    HIRED:"Hired",
    DESIGNATION:"Designation",
    DATE:"Date",
    STATUS:"Status",
    DOWNLOADS:"Downloads",
    FIVE_INTO_FIVE:"5/5",
    DASHBOARD:"Dashboard",
    RECENTLY_JOB_POST:"Recently Job post",
    CONGRATULATIONS_YOUR_CERTIFICATION_IS_COMPLETE:"Congratulations Your Certification is Complete.",
    VIEW_CERTIFICATE:"View certificate",
    CERTIFICATION_VALIDATION_IS_YEAR_ONLY:"*Certification validation is 1 year only",
    SHARE:"Share:",
    DOWNLOAD:"Download",
    EARN_BADGE:"Earn Badge",
    APPLICANT:"Applicant",
    AWAITING:"Awaiting",
    CONTACTING:"Contacting",
    JOBS:"Jobs",
    DATE_POSTED:"Date posted",
    JOB_POSTING:"Job posting",
    PREVIEW:"Preview",
    EMPLOYMENT_TYPE:"Employment Type",
    PICK_ONE_OR_MULTIPLE_OPTION:"Pick one or multiple option",
    WORKING_SCHEDULE:"Working Schedule",
    YOU_CAN_PICK_MULTIPLE_WORK_SCHEDULES:"You can pick multiple work schedules.",
    PICK_WORKING_SCHEDULE:"Pick working schedule",
    SALARY:"Salary",
    CHOOSE_HOW_YOU_PREFER_TO_PAY_FOR_THIS_JOB:"Choose how you prefer to pay for this job.",
    HOURLY:"Hourly",
    MONTHLY:"Monthly",
    HOURLY_RATE:"Hourly rate",
    INTERVIEW_TIME:"Interview Time",
    CHOOSE_YOUR_INTERVIEW_TIME_SLOT:"Choose your interview time slot",
    BACK:"Back",
    NEXT:"Next",
    TELL_US_ABOUT_THE_ROLE:"Tell us about the role",
    SKILLS:"Skills",
    ADD_SKILL_KEYWORDS_TO_MAKE_YOUR_JOB:"Add skill keywords (max 10) to make your job more visible to the right candidates.",
    ADD_SKILL:"Add Skill",
    I_AM_HIRING_MULTIPLE_CANDIDATES:"I am hiring multiple candidates",
    THIS_WILL_BE_DISPLAYED_ON_JOB_PAGE_FOR_CANDIDATES_SEE:" This will be displayed on job page for candidates to see.",
    HIRING_MULTIPLE_CANDIDATES:"Hiring multiple candidates?",
    ARE_YOU_HIRING_MANAGER:"Are you a hiring manager?",
    THE_HIRED_CANDIDATE_WILL_WORK_IN_REPORTING_CHAIN:" The hired candidate will work in your reporting chain.",
    COMPANY:"Company",
    YOUR_COMPANY_NAME:"Your Company name",
    WORKPLACE_TYPE:"Workplace typ",
    JOB_POSTING_LOCATION:"Job posting location",
    WHICH_OPTION_BEST_DESCRIBE_THIS_JOBS_LOCATION:" Which option best describe this job’s location?",
    CITY:"City",
    AREA:"Area",
    PINCODE:"Pincodes",
    STREET_ADDRESS:"Street address",
    LEARN_AND_EARN:"Learn & Earn",
    TIME_REMAINING:"Time remaining",
    REFER_THIS_ARTICLE_LINK:"Refer this article Link",
    QUIZ_INFO:"Quiz info",
    QUIZ_JOINING_TIME: "Quiz Joining Time 8:00 PM to 8:45 PM",
    Join_Now:"Join Now",
    REGISTRATION:"Registration",
    REGISTRATION_INFO:"Registration info",
    REGISTRATION_TIME:"Registration Time 8:00 AM to 12:00 PM",
    RESULT_ANNULMENT_TIME:"Result annulment 9:15 PM",
    WINNING_PRIZE_REDEEM_WITH_HOURS_AFTER_TEST_COMPLETE:"Winning Prize redeem with in 24 Hours after test complete",
    ONLY_WHEN_YOU_HAVE_CERTIFICATION_CAN_YOU_DO_LEARN_AND_EARN_USE:"Only when you have the certification can you do learn and earn use.",
    GO_TO_CERTIFICATION:"Go to Certification",
    CERTIFYRECRUIT_STREAMLINES_YOUR_ENTIRE_RECRUITING_PROCESS:" CertifyRecruit streamlines your entire recruiting process, so you can find the best people for your team, quickly and easily",
    START_NOW_ITS_FREE:" Start now - it's free",
    SCHEDULE_A_DEMO:"Schedule a demo",
    REDIRECT_TO_CALENDLY:"Redirect to Calendly",
    INDIVIDUAL:"Individual",
    EMPLOYEE:"Employee",
    Hiring:"Hiring",
    WEBNOVA_INFOTECH:"Webnova Infotech",
    NEW_YOUR_USA:"New Your, USA",
    BASIC_DETAIL:"Basic Detail",
    Company_Detail:"Company Detail",
    KYC_Compliance_Detail:"KYC Compliance Detail",
    USERNAME:"Username",
    ROLE:"Role",
    PHONE_NUMBER:"Phone Number",
    WEBSITE_URL:"Website URL",
    OWNER:"Owner",
    COMPANY_MAILING_ADDRESS:"Company mailing address",
    PAN_NUMBER:"PAN Number",
    NAME_ON_PAN_CARD:"Name on PAN Card",
    SAVE:"Save",
    COMPANY_TYPE:"Company Type",
    COMPANY_NAME:"Company Name",
    CHOOSE_YOUR_PLAN:" Choose your plan",
    YEARLY:"Yearly",
    BASIC_PLAN:"Basic Plan",
    Month:"/Month",
    MOST_POPULAR:"Most Popular",
    STANDARD_PLAN:"Standard Plan",
    BUSINESS_PLAN:"Business Plan",
    GET_STARTED:"Get Started",
    SEARCH_CVS:"Search CVs",
    AVAILABLE:"Available",
    KEYWORD:"Keyword",
    SERVER_SIDE:"Server Side",
    ADD_KEYWORD:"Add keyword",
    DATE_UPLOADED:"Date Uploaded",
    JAVA:"Java",
    CSS:"Css",
    MATCHING:"Matching",
    ADD_USER:"Add User",
    HOURS:"Hours",
    MINS:"Mins",
    SECS:"Secs",
    QUIZ_DETAIL:"Quiz Detail",
    START_DATE_TIME:"Start Date Time",
    MARKS_PER_QUESTION:"Marks Per Question",
    MAX_TAB_SWITCH_ALLOW:"Max Tab Switch Allow",
    DURATION:"Duration",
    NEGATIVE_MARKS_PER_QUESTION:"Negative Marks Per Question",
    QUESTION_PALETTE:"Question Palette"
}

const ROUTE={
    SIGN_UP:"/signUp",
    LOGIN:"/login",
    SUCCESSFULL_FORGOT_PASSWORD:"/login/forgotPass/newPass/successful",
    ACTIVE_JOB:"/dashboard/active_job",
    HIRED:"/dashboard/hired",
    APPLICANTS:"/job/applicants",
    EMPLOYMENT_TYPE:"/job_posting/employment_Type",
    MYPROFILE:"/myProfile",
    QUIZINFO:"/learn&earn/quizInfo",
    QUIZMCQS:"/learn&earn/quizMCQs",
    MAIN:"/main"

    
}
const EMAIlREGEX = /^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/g;

export {TEXT,ROUTE,EMAIlREGEX}
