import { Icons } from '@/svg';
import mongoose from 'mongoose';

const EMAIlREGEX =
  /^[a-zA-Z0-9]+([._-]?[a-zA-Z0-9]+)*@[a-zA-Z0-9]+([.-]?[a-zA-Z0-9]+)*\.[a-zA-Z]{2,}$/g;
// const EMAIlREGEX = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$/;
// const EMAIlREGEX = /^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/g;

const ROUTE = {
  JOB: '/job',
  MAIN: '/main',
  LOGIN: '/login',
  SIGN_UP: '/signup',
  PRICING: '/pricing',
  DASHBOARD: '/dashboard',
  MYPROFILE: '/myProfile',
  HIRED: '/dashboard/hired',
  SEARCH_CVS: '/search_CVs',
  JOb_POST: '/job_posting',
  JOb_DETAILS: 'job/details',
  APPLICANTS: '/job/applicants',
  QUIZINFO: '/learn&earn/quizInfo',
  QUIZMCQS: '/learn&earn/quizMCQs',
  ACTIVE_JOB: '/dashboard/active_job',
  EMPLOYMENT_TYPE: '/job_posting/employment_Type',
  SUCCESSFULL_FORGOT_PASSWORD: '/login/forgotPass/newPass/successful',
  JOB_AWAITING: '/job/awaiting',
  JOB_APPLICANTS: '/job/applicants',
  JOB_CONTACTING: '/job/contacting',
  JOB_HIRED: '/job/hired',
};

const TEXT = {
  UPLOAD: 'Upload',
  OR: 'or',
  CTC: 'CTC',
  POST: 'Post',
  USA: 'Usa',
  CSS: 'Css',
  SEND: 'Send',
  DONE: 'Done',
  NAME: 'Name',
  EDIT: 'Edit',
  VIEW: 'View',
  DATE: 'Date',
  JOBS: 'Jobs',
  ROLE: 'Role',
  SAVE: 'Save',
  BACK: 'Back',
  NEXT: 'Next',
  JAVA: 'Java',
  MINS: 'Mins',
  SECS: 'Secs',
  CITY: 'City',
  AREA: 'Area',
  YEAR: 'Year',
  EMAIL: 'Email',
  SCORE: 'Score',
  MONTH: 'Month',
  HIRED: 'Hired',
  OWNER: 'Owner',
  HOURS: 'Hours',
  SHARE: 'Share:',
  Month: '/Month',
  LOG_IN: 'Log In',
  CANCEL: 'Cancel',
  DELETE: 'Delete',
  STATUS: 'Status',
  SALARY: 'Salary',
  HOURLY: 'Hourly',
  SKILLS: 'Skills',
  Hiring: 'Hiring',
  YEARLY: 'Yearly',
  PRICING: 'Pricing',
  LOG_OUT: 'Log out',
  SIGN_UP: 'Sign up',
  PREVIEW: 'Preview',
  MONTHLY: 'Monthly',
  KEYWORD: 'Keyword',
  COMPANY: 'Company',
  PINCODE: 'Pincodes',
  PASSWORD: 'Password',
  LOCATION: 'Location',
  JOB_POST: 'Job Post',
  DOWNLOAD: 'Download',
  AWAITING: 'Awaiting',
  EMPLOYEE: 'Employee',
  USERNAME: 'Username',
  MATCHING: 'Matching',
  ADD_USER: 'Add User',
  DURATION: 'Duration',
  Join_Now: 'Join Now',
  COMPLETE: 'Complete',
  FIVE_INTO_FIVE: '5/5',
  HI_THERE: ' Hi there!',
  JOB_TITLE: 'Job title',
  DOWNLOADS: 'Downloads',
  DASHBOARD: 'Dashboard',
  APPLICANT: 'Applicant',
  ADD_SKILL: 'Add Skill',
  AVAILABLE: 'Available',
  QUIZ_INFO: 'Quiz info',
  FULL_NAME: 'Full Name',
  DEPARTMENT: 'Department',
  EXPERIENCE: 'Experience',
  ACTIVE_JOB: 'Active Job',
  EARN_BADGE: 'Earn Badge',
  CONTACTING: 'Contacting',
  INDIVIDUAL: 'Individual',
  PAN_NUMBER: 'PAN Number',
  BASIC_PLAN: 'Basic Plan',
  SEARCH_CVS: 'Search CVs',
  GO_TO_LOGIN: 'Go to login',
  JOB_DETAILS: 'Job details',
  DESIGNATION: 'Designation',
  DATE_POSTED: 'Date posted',
  JOB_POSTING: 'Job posting',
  HOURLY_RATE: 'Hourly rate',
  WEBSITE_URL: 'Website URL',
  GET_STARTED: 'Get Started',
  SERVER_SIDE: 'Server Side',
  ADD_KEYWORD: 'Add keyword',
  QUIZ_DETAIL: 'Quiz Detail',
  Get_Started: 'Get Started!',
  OUT_SIDE_USA: 'Outside USA',
  EDIT_PROFILE: 'Edit profile',
  MONTHLY_RATE: 'Monthly rate',
  SUCCESSFULLY: 'Successfully',
  COMPANY_INFO: 'Company Info',
  ADD_EMPLOYEE: 'Add Employee',
  TWO_WEEKS_AGO: '2 weeks ago',
  BASIC_DETAIL: 'Basic Detail',
  PHONE_NUMBER: 'Phone Number',
  COMPANY_TYPE: 'Company Type',
  COMPANY_NAME: 'Company Name',
  MOST_POPULAR: 'Most Popular',
  REGISTRATION: 'Registration',
  NEW_YOUR_USA: 'New Your, USA',
  STANDARD_PLAN: 'Standard Plan',
  BUSINESS_PLAN: 'Business Plan',
  DATE_UPLOADED: 'Date Uploaded',
  GO_TO_PROFILE: 'Go to profile',
  LEARN_AND_EARN: 'Learn & Earn',
  WORKPLACE_TYPE: 'Workplace type',
  RESET_PASSWORD: 'Reset Password',
  INTERVIEW_TIME: 'Interview Time',
  Company_Detail: 'Company Detail',
  STREET_ADDRESS: 'Street address',
  TIME_REMAINING: 'Time remaining',
  RESET_VIA_EMAIL: 'Reset via Email',
  EMPLOYMENT_TYPE: 'Employment Type',
  SCHEDULE_A_DEMO: 'Schedule a demo',
  START_DATE_TIME: 'Start Date Time',
  FORGOT_PASSWORD: 'Forgot password?',
  CITY_NAMES: 'Surat, Gujrat, India.',
  CURRENT_LOCATION: 'Current location',
  TOTAL_EXPERIENCE: 'Total experience',
  SET_NEW_PASSWORD: 'Set new password',
  CONFIRM_PASSWORD: 'Confirm password',
  VIEW_CERTIFICATE: 'View certificate',
  WORKING_SCHEDULE: 'Working Schedule',
  WEBNOVA_INFOTECH: 'Webnova Infotech',
  NAME_ON_PAN_CARD: 'Name on PAN Card',
  QUESTION_PALETTE: 'Question Palette',
  CHOOSE_YOUR_PLAN: ' Choose your plan',
  RECENTLY_JOB_POST: 'Recently Job post',
  YOUR_COMPANY_NAME: 'Your Company name',
  REGISTRATION_INFO: 'Registration info',
  MARKS_PER_QUESTION: 'Marks Per Question',
  LOG_IN_WITH_GOOGLE: ' Log in with Google',
  SIGN_UP_WITH_GOOGLE: 'Sign up with Google',
  JOB_POSTING_LOCATION: 'Job posting location',
  START_NOW_ITS_FREE: " Start now - it's free",
  REDIRECT_TO_CALENDLY: 'Redirect to Calendly',
  MAX_TAB_SWITCH_ALLOW: 'Max Tab Switch Allow',
  COMPLETE_YOUR_PROFILE: 'Complete your profile',
  PICK_WORKING_SCHEDULE: 'Pick working schedule',
  KYC_Compliance_Detail: 'KYC Compliance Detail',
  DONT_HAVE_AN_ACCOUNT: "Don't have an account? ",
  THANK_YOU_FOR_SIGN_UP: 'Thank you for sign up!',
  TELL_US_ABOUT_THE_ROLE: 'Tell us about the role',
  RESULT_ANNULMENT_TIME: 'Result annulment 9:15 PM',
  COMPANY_MAILING_ADDRESS: 'Company mailing address',
  REFER_THIS_ARTICLE_LINK: 'Refer this article Link',
  ALREADY_HAVE_AN_ACCOUNT: 'Already have an account? ',
  USER_INTERFACE_EXPERT: 'User Interface Expert (WFH)',
  HIRING_MULTIPLE_CANDIDATES: 'Hiring multiple candidates?',
  QUIZ_JOINING_TIME: 'Quiz Joining Time 8:00 PM to 8:45 PM',
  WELCOME_BACK_TO_CERTIFY: 'Welcome back to CertifyRecruit.',
  PICK_ONE_OR_MULTIPLE_OPTION: 'Pick one or multiple option',
  NEGATIVE_MARKS_PER_QUESTION: 'Negative Marks Per Question',
  REGISTRATION_TIME: 'Registration Time 8:00 AM to 12:00 PM',
  YOUR_NEW_JOURNEY_BEGINS_NOW: 'Your New Journey Begins Now.',
  MUST_BE_AT_LEAST_CHARACTERS: 'Must be at least 8 characters',
  YOUR_PASSWORD_HAS_BEEN_RESET: 'your password has been reset',
  CHOOSE_YOUR_INTERVIEW_TIME_SLOT: 'Choose your interview time slot',
  YOU_CAN_PICK_MULTIPLE_WORK_SCHEDULES: 'You can pick multiple work schedules.',
  CHOOSE_HOW_YOU_PREFER_TO_PAY_FOR_THIS_JOB:
    'Choose how you prefer to pay for this job.',
  PLEASE_SELECT_OPTION_TO_RECEIVE_PASSWORD_RESET_LINK:
    'Please select option to receive password reset link.',
  YOU_WILL_BE_PROVIDE_A_UNIQUE:
    'You will be provide a unique password reset link to your registered email address.',
  CONGRATULATIONS_YOUR_CERTIFICATION_IS_COMPLETE:
    'Congratulations Your Certification is Complete.',
  CERTIFICATION_VALIDATION_IS_YEAR_ONLY:
    '*Certification validation is 1 year only',
  ADD_SKILL_KEYWORDS_TO_MAKE_YOUR_JOB:
    'Add skill keywords (max 10) to make your job more visible to the right candidates.',
  I_AM_HIRING_MULTIPLE_CANDIDATES: 'I am hiring multiple candidates',
  THIS_WILL_BE_DISPLAYED_ON_JOB_PAGE_FOR_CANDIDATES_SEE:
    ' This will be displayed on job page for candidates to see.',
  ARE_YOU_HIRING_MANAGER: 'Are you a hiring manager?',
  THE_HIRED_CANDIDATE_WILL_WORK_IN_REPORTING_CHAIN:
    ' The hired candidate will work in your reporting chain.',
  WHICH_OPTION_BEST_DESCRIBE_THIS_JOBS_LOCATION:
    " Which option best describe this job's location?",
  WINNING_PRIZE_REDEEM_WITH_HOURS_AFTER_TEST_COMPLETE:
    'Winning Prize redeem with in 24 Hours after test complete',
  ONLY_WHEN_YOU_HAVE_CERTIFICATION_CAN_YOU_DO_LEARN_AND_EARN_USE:
    'Only when you have the certification can you do learn and earn use.',
  GO_TO_CERTIFICATION: 'Go to Certification',
  CERTIFYRECRUIT_STREAMLINES_YOUR_ENTIRE_RECRUITING_PROCESS:
    ' CertifyRecruit streamlines your entire recruiting process, so you can find the best people for your team, quickly and easily',
};

const USER_ROLE = {
  EMPLOYEE: 'employee',
  INDIVIDUAL: 'individual',
};

const SIDE_BAR_DATA = {
  admin: [],
  individual: [
    {
      path: 'dashboard',
      title: 'Dashboard',
      icon: Icons.Dashboard,
    },
    {
      path: 'job',
      title: 'Job',
      icon: Icons.Job,
    },
    {
      icon: Icons.Learn,
      path: 'learn&earn',
      title: 'Learn & Earn',
    },
    {
      path: 'certification',
      title: 'Certification',
      icon: Icons.Certificate,
    },
    {
      path: 'pricing',
      title: 'Pricing',
      icon: Icons.Pricing,
    },
  ],
  employee: [
    {
      path: 'dashboard',
      title: 'Dashboard',
      icon: Icons.Dashboard,
    },
    {
      path: 'job_posting',
      title: 'Job Posting',
      icon: Icons.Job,
    },
    {
      path: 'job',
      title: 'Job',
      icon: Icons.Job,
    },
    {
      path: 'pricing',
      title: 'Pricing',
      icon: Icons.Pricing,
    },
  ],
};

const createModal = (name: string, schema: any) =>
  mongoose.models?.[name] || mongoose.model(name, schema);

const calculatePercentage = (values: any, pr: any) => {
  const tab1Complete = Object.values(values).filter((val) => val !== '').length;
  const totalFields = Object.keys(values).length;
  const totalCompleted = tab1Complete;
  const percentage = (totalCompleted / totalFields) * pr;
  return percentage.toFixed(2);
};

export {
  TEXT,
  ROUTE,
  EMAIlREGEX,
  USER_ROLE,
  SIDE_BAR_DATA,
  createModal,
  calculatePercentage,
};
