const API_CONSTANT = {
  JOB: '/job',
  LOGIN: '/signin',
  CITIES: '/cities',
  DEGREE: '/degree',
  STATES: '/states',
  SIGN_UP: '/signup',
  PROFILE: '/profile',
  COLLEGE: '/collage',
  COUNTRY: '/country',
  CATEGORY: '/category',
  LANGUAGE: '/language',
  QUESTION: '/question',
  JOB_APPLY: '/job-apply',
  UPLOAD_FILE: '/s3-upload',
  JOB_SEARCH: '/job-search',
  JOB_DELETE: '/delete-job',
  JOB_DETAILS: '/job-details',
  CHECK_ANSWER: '/check-answer',
  DELETE_RESUME: '/delete-resume',
  DASHBOARD_JOB: '/dashboard-job',
  SEND_EXAM_LINK: '/send-exam-link',
  QUIZ_RESULTS: '/le-today-results',
  RESET_PASSWORD: '/reset-password',
  FORGOT_PASSWORD: '/forgot-password',
  UPDATE_APPLY_JOB: '/update-apply-job',
  CHECK_LEARN_ANSWER: '/check-le-answer',
  UPDATE_LE_DETAILS: '/update-le-details',
  LEARN_AND_EARN_QUESTION: '/learn-and-earn-question',
};

export { API_CONSTANT };
