import "./globals.css";
import AuthProvider from "./Providers";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import { getServerSession } from "next-auth";
import "react-toastify/dist/ReactToastify.css";
import { AppProvider } from "@/context/AppProvider";
import { ToastContainer, toast } from "react-toastify";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer />
        <AppProvider>
          <AuthProvider session={session}>{children} </AuthProvider>
        </AppProvider>
      </body>
    </html>
  );
}
